### ISSUE TITLE
Figure out the limits of Qemu

### ISSUE THREAD

**Issue by mlevin23** [mlevin23/Zephyr22#4]
Right now we are using Qemu very basically, we need to figure out everything that Qemu can and cannot do to see what the general limitations of our project as far as Qemu goes.

**Comment by sgoggins** [comment]
If you hit a dead end here, lets figure out how you might be able to pivot. Have you met with Group 2 to see how they might advise you to go?

**Comment by mlevin23** [comment]
Yeah we did meet with groups and we now understand that the focus needs to move away from the limitations of Qemu and now need to focus on the net tools/online aspect of Zephyr instead of simulating everything directly in Qemu.

**Comment by mlevin23** [comment]
Qemu is no longer our focus as it just holds the client for the lwm2m instance. As such we have decided that it better to direct our time on focusing on the front end, and the passing of the lwm2m client as a prototype to show client passing capabilities.
