### ISSUE TITLE
Get a better understanding of Zephyr's C code

### ISSUE THREAD

**Issue by mlevin23** [mlevin23/Zephyr22#5]
Right now it seems like Zephyr uses a modified version of C code that does not include (so far that we have seen) things like printf and scanf. There may be more that Zephyr does not include but we have not encountered anything like this yet.

**Comment by sgoggins** [comment]
After meeting with group 2, do you have a sense of how you might "pivot" if this level of effort exceeds what is possible for this course?

**Comment by mlevin23** [comment]
I don't know if it was group 2 that we met with specifically on Thursday, however we do have a much better idea of the direction to take the project in, and steps that we can take to hit our overall goal in what we want it to look like.

**Comment by mlevin23** [comment]
More specifically, we now know that we need to start working with net tools in order to set up a front end for Zephyr, using Qemu as an emulation for a board back-end.

**Comment by mlevin23** [comment]
It seems that the back end is mostly completed in the samples so we are going to focusing on creating our front end through the leshan server using html/css/javascript.
