### ISSUE TITLE
Building the front end

### ISSUE THREAD

**Issue by mlevin23** [mlevin23/Zephyr22#6]
Currently our goal is to build a functioning front end through HTML and css. We currently have a pretty detailed mock-up of what we would like the front end to look like. Our goal for sprint 3 is to build the login/welcome screen along with completing a front end for one of our use cases. While our design may be subject to change, this is a general outline of what we want it to end up being.
![05d737bd8eb24ad4b05e62467acc1d1a](https://user-images.githubusercontent.com/32828119/57100201-ef51c400-6ce3-11e9-8610-965efde38d7b.png)

**Comment by kmeyer1212** [comment]
As of right now, we have the lighting use case working. As we do not have sensor information currently, we still have to work on the back end portion for Sprint 4, but the front end is working great and meets our goal.

**Comment by CMPerniciaro** [comment]
We have finished the front end, all functions have their own page.
